#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CameraSample.Droid.Resource", IsApplication=true)]

namespace CameraSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CrossPlatformLibrary.Camera.Resource.Drawable.camera = global::CameraSample.Droid.Resource.Drawable.camera;
			global::CrossPlatformLibrary.Camera.Resource.Drawable.camera_switch = global::CameraSample.Droid.Resource.Drawable.camera_switch;
			global::CrossPlatformLibrary.Camera.Resource.Drawable.round_button = global::CameraSample.Droid.Resource.Drawable.round_button;
			global::CrossPlatformLibrary.Camera.Resource.Id.container = global::CameraSample.Droid.Resource.Id.container;
			global::CrossPlatformLibrary.Camera.Resource.Id.switchCameraButton = global::CameraSample.Droid.Resource.Id.switchCameraButton;
			global::CrossPlatformLibrary.Camera.Resource.Id.takePictureButton = global::CameraSample.Droid.Resource.Id.takePictureButton;
			global::CrossPlatformLibrary.Camera.Resource.Id.texture = global::CameraSample.Droid.Resource.Id.texture;
			global::CrossPlatformLibrary.Camera.Resource.Layout.activity_camera = global::CameraSample.Droid.Resource.Layout.activity_camera;
			global::CrossPlatformLibrary.Camera.Resource.Layout.fragment_camera2_basic = global::CameraSample.Droid.Resource.Layout.fragment_camera2_basic;
			global::CrossPlatformLibrary.Camera.Resource.String.picture = global::CameraSample.Droid.Resource.String.picture;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::CameraSample.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::CameraSample.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int camera_switch = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int round_button = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int container = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int switchCameraButton = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int takePictureButton = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int texture = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_camera = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_camera2_basic = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int picture = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
