#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidCameraApp.Resource", IsApplication=true)]

namespace AndroidCameraApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CrossPlatformLibrary.Camera.Resource.Id.container = global::AndroidCameraApp.Resource.Id.container;
			global::CrossPlatformLibrary.Camera.Resource.Id.picture = global::AndroidCameraApp.Resource.Id.picture;
			global::CrossPlatformLibrary.Camera.Resource.Id.texture = global::AndroidCameraApp.Resource.Id.texture;
			global::CrossPlatformLibrary.Camera.Resource.Layout.activity_camera = global::AndroidCameraApp.Resource.Layout.activity_camera;
			global::CrossPlatformLibrary.Camera.Resource.Layout.fragment_camera2_basic = global::AndroidCameraApp.Resource.Layout.fragment_camera2_basic;
			global::CrossPlatformLibrary.Camera.Resource.String.picture = global::AndroidCameraApp.Resource.String.picture;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int MyButton = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int button1 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int button2 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int button3 = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int container = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int imageView1 = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int picture = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int texture = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_camera = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_camera2_basic = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int picture = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
